project                  = "wekaio-rnd"
region                   = "europe-west1"
zone                     = "europe-west1-b"
prefix                   = "weka"
host_project             = "test-tf-vars"
bucket_location          = "EU"
subnets_cidr_range       = ["10.0.0.0/24", "10.1.0.0/24", "10.2.0.0/24", "10.3.0.0/24"]
shared_vpcs              = ["host-vpc-shared-1", "host-vpc-shared-2"]
host_shared_range        = ["10.13.0.0/24", "10.14.0.0/24"]
nics_number              = 4
cluster_size             = 5
install_url              = "gs://weka-installation/weka-4.0.0.68-gcp-beta.tar"
machine_type             = "c2-standard-8"
nvmes_number             = 2
username                 = "weka"
weka_version             = "4.0.0.68-gcp-beta"
yum_repo_server          = "http://yum.weka.private.net"
cluster_name             = "poc"
vpc_connector_range      = "10.8.0.0/28"
sa_name                  = "deploy-sa"
create_cloudscheduler_sa = true
private_network          = true
weka_image_name          = "centos-7-v20220719"
weka_image_project       = "centos-cloud"
set_peering              = true
create_vpc_connector     = true