variable "project_id" {
  type        = string
  description = "Project id"
}

variable "cluster_name" {
  type        = string
  description = "Cluster prefix for all resources"
  validation {
    condition     = length(var.cluster_name) <= 37
    error_message = "The cluster name maximum allowed length is 37."
  }
}

variable "nics_numbers" {
  type        = number
  description = "Number of nics per host"
  default = -1

  validation {
    condition     = var.nics_numbers == -1 || var.nics_numbers > 0
    error_message = "The nics_number value can take values > 0 or -1 (for using defaults)."
  }
}

variable "zone" {
  type        = string
  description = "Zone name"
}

variable "machine_type" {
  type        = string
  description = "Weka cluster backends machines type"
  default = "c2-standard-8"
  validation {
    condition = contains(["c2-standard-8", "c2-standard-16"], var.machine_type)
    error_message = "Machine type isn't supported"
  }
}

variable "region" {
  type        = string
  description = "Region name"
}

variable "protocol" {
  type        = string
  description = "Name of the protocol."
  default     = "NFS"

  validation {
    condition     = contains(["NFS", "SMB"], var.protocol)
    error_message = "Allowed values for protocol: NFS, SMB."
  }
}

variable "secondary_ips_per_nic" {
  type        = number
  description = "Number of secondary IPs per single NIC per protocol gateway virtual machine."
  default     = 2
}

variable "subnets_list" {
  type        = list(string)
  description = "list of subnet names"
}

variable "yum_repo_server" {
  type        = string
  description = "yum repo server address"
  default     = ""
}

variable "gateways_number" {
  type        = number
  description = "The number of virtual machines to deploy as protocol gateways."
}

variable "gateways_name" {
  type        = string
  description = "The protocol group name."
}

variable "interface_group_name" {
  type        = string
  description = "Interface group name."
  default     = "weka-ig"

  validation {
    condition     = length(var.interface_group_name) <= 11
    error_message = "The interface group name should be up to 11 characters long."
  }
}

variable "client_group_name" {
  type        = string
  description = "Client access group name."
  default     = "weka-cg"
}

variable "vm_username" {
  type        = string
  description = "The user name for logging in to the virtual machines."
  default     = "weka"
}

variable "assign_public_ip" {
  type        = bool
  description = "Determines whether to assign public ip."
}

variable "disk_size" {
  type        = number
  description = "The disk size."
}

variable "traces_per_frontend" {
  default     = 10
  type        = number
  description = "The number of traces per frontend ionode. Traces are low-level events generated by Weka processes and are used as troubleshooting information for support purposes. Protocol gateways have only frontend ionodes."
}

variable "frontend_num" {
  type        = number
  default     = 1
  description = "The number of frontend ionodes per instance."
}

variable "install_weka_url" {
  type        = string
  description = "The URL of the Weka release download tar file."

  validation {
    condition     = length(var.install_weka_url) > 0
    error_message = "The URL should not be empty."
  }
}

variable "sa_email" {
  type        = string
  description = "service account email"
}

variable "backend_lb_ip" {
  type        = string
  description = "Backend Load balance private ip"
}

variable "source_image_id" {
  type        = string
  description = "Source image id"
}

variable "weka_token_id" {
  type       = string
  description = "Id of weka token"
}

variable "weka_password_id" {
  type       = string
  description = "Id of weka password"
}

variable "proxy_url" {
  type        = string
  description = "Weka home proxy url"
  default     = ""
}