name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ci

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/public_vpc

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Copy Terraform State
        run: cp "../../ci/deployment/state.tf" .

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -var-file=../../ci/deployment/terraform.tfvars -var="get_weka_io_token=$GET_WEKA_IO_TOKEN" -auto-approve
        env:
          GET_WEKA_IO_TOKEN: ${{ secrets.GET_WEKA_IO_TOKEN }}

      - name: Wait for weka cluster
        run: ../../ci/deployment/wait_for_cluster.sh 7 30

      - name: Scale up
        run: >
          gcloud functions call weka-poc-resize
          --project wekaio-ci
          --region europe-west1
          --data '{"value": 8}'
          --gen2

      - name: Wait for weka cluster
        run: ../../ci/deployment/wait_for_cluster.sh 8 15

      - name: Scale down
        run: >
          gcloud functions call weka-poc-resize
          --project wekaio-ci
          --region europe-west1
          --data '{"value": 6}'
          --gen2

      - name: Wait for weka cluster
        run: ../../ci/deployment/wait_for_cluster.sh 6 15

      - name: Terminate cluster
        if: always()
        run: >
          gcloud functions call weka-poc-terminate-cluster
          --project wekaio-ci
          --region europe-west1
          --data '{"name": "poc"}'
          --gen2

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -var-file=../../ci/deployment/terraform.tfvars -var="get_weka_io_token=$GET_WEKA_IO_TOKEN" -auto-approve
        env:
          GET_WEKA_IO_TOKEN: ${{ secrets.GET_WEKA_IO_TOKEN }}
